#+BEGIN_HTML
<a href="https://img.shields.io/badge/Emacs%20-%2029.1%20-%20orange">
  <img src="https://img.shields.io/badge/Emacs%20-%2029.1%20-%20orange" alt="Emacs Version">
</a>
#+END_HTML

* entr-runner.el

A complete hot reload package that let you choose the command you want and can watch multiple files.

** ❓ Why?

I was coding a website with thymeleaf on springboot but I wasn't able to make the hotreload functionality to work properly for me. (Skill issues I know)
That lead me to this package. It permits to choose one or multiple files/directories or both then write a custom command that will run each time these files are changed.


** 💾 Installation

*** Straight
#+BEGIN_SRC elisp
(use-package entr-runner
  :straight (entr-runner :type git :host github :repo "SamuelVanie/entr-runner.el"))
#+END_SRC

*** Doom Emacs
#+BEGIN_SRC elisp
(package! entr-runner
  :recipe (:host github :repo "SamuelVanie/entr-runner.el"))
#+END_SRC

# *** MELPA
# #+BEGIN_SRC elisp
# (use-package youdotcom
#   :bind ("C-c y" . youdotcom-enter))
# #+END_SRC


** 💻 Usage


Two possibilities :
- You can mark your files or directories inside dired (use the "*" key to do so), then run the command =entr-runner-dired=. That command will prompt you info about the flags that you wish to add to the command and there it is.
- You can also use the command =entr-runner-regex= that will prompt you for regex that will select all the files from the /default-directory/ and run the command that you will choose on them.

You can stop the process by running the command =entr-runner-kill-process=. That will kill the process in charge of watching the files.

When you run one of the entr commands, a special buffer will be created that is called *entr-runner*. This is the buffer in which you can check the logs of the command you ran.



** 👊 Contributing

- If you find a bug or have an idea for an improvement, please open an issue about it.
- If you want to contribute, you can open a pull request and I will be happy to review it.
- If you want to add a new feature, please open an issue first to discuss about it.
- If you want to support me, you can star the repository.
